name: Makefile CI

on:
  push:
    branches: [ "pmoineau.v0.3.0" ]
  pull_request:
    branches: [ "pmoineau.v0.3.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.11  # Use an appropriate Go version

    - name: Clean Go Cache
      run: go clean -cache

    - name: Clean
      run: |
        rm -rf vendor

    - name: Make
      run: |
        ls -ltra
        cat /etc/os-release
        sudo apt-get install -y libcairo2-dev
        go mod tidy
        go mod vendor
        which go
        cp -r /opt/hostedtoolcache/go/1.20.7/x64/pkg/mod/cache/download/* ./vendor/
        make
        ls -ltra
